using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class JawabanQuiz : MonoBehaviour
{
    public GameObject benar, salah;
    // Start is called before the first frame update
    void Start()
    {

    }

    public void jawaban(bool JawabanQuiz)
    {
        if (JawabanQuiz)
        {
            benar.SetActive(false);
            benar.SetActive(true);
            //int skor = PlayerPrefs.GetInt("skor")+10;
           // PlayerPrefs.SetInt("skor", skor);
        }
        else
        {
            salah.SetActive(false);
            salah.SetActive(true);
        }
        gameObject.SetActive(false);
        transform.parent.GetChild(gameObject.transform.GetSiblingIndex() + 1).gameObject.SetActive(true);
    }

    // Update is called once per frame
    void Update()
    {

    }
}
